language: rust
rust: 
  - nightly
  
install:
  - rustup target add wasm32-unknown-unknown
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install v10.5
  - BINARYEN_TAG=1.38.32
  - wget -O /tmp/binaryen.tar.gz https://github.com/WebAssembly/binaryen/releases/download/1.38.32/binaryen-$BINARYEN_TAG-x86_64-linux.tar.gz
  - tar -zxvf /tmp/binaryen.tar.gz
  - ls
  - export PATH=$PATH:$PWD/binaryen-$BINARYEN_TAG/
  

script:
  - cd lib
  - cargo test
  - cd ../examples/crate
  - cargo test
  - cd ..
  - npm install
  - npm run bundle
  
deploy:
  local_dir: examples/dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
