language: rust
rust: 
  - nightly
  
install:
  - rustup target add wasm32-unknown-unknown
  - cargo install wasm-bindgen-cli

script:
  - cd lib
  - cargo test --features webgl_1
  - cargo test --features webgl_2
  - cd ../examples/crate
  - cargo test --features webgl_1
  - cargo test --features webgl_2
  - cd ..
